template_path: bridgeworker.yaml
stack_name: bridgeworker-prod
parameters:
  AwsDefaultVpcId: vpc-08383f78519fe72ef
  AwsSnsNotificationEndpoint: biaffect-bridge-ops@googlegroups.com
  BackfillBucket: org-biaffectbridge-backfill-prod
  BridgeEnv: prod
  BridgeUser: biaffect
  BridgeWorkerEmail: biaffect-bridge-ops+worker@googlegroups.com
  BridgeWorkerStudy: api
  BridgeWorkerPassword: !ssm /bridgeworker-prod/BridgeWorkerPassword
  EC2InstanceType: t3a.2xlarge
  Env: production
  JavaHeapSize: 24g
  RawHealthDataBucket: org-biaffectbridge-rawhealthdata-prod
  SynapseAccessToken:  !ssm /bridgeworker-prod/SynapseAccessToken
  SynapsePrincipalId: '3509740'
  SynapseUser: BiaffectBridgeExporter
  UploadBucket: org-biaffectbridge-upload-prod
  UploadCertBucket: org-biaffectbridge-upload-cms-cert-prod
  UploadPrivateKeyBucket: org-biaffectbridge-upload-cms-priv-prod
  UserDataBucket: org-sagebridge-biaffectdata-prod
  ParticipantRosterBucket: org-biaffectbridge-participantroster-prod
  WorkerSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/381492192635/Bridge-WorkerPlatform-Request-prod
