template_path: bridgeworker.yaml
stack_name: bridgeworker-prod
parameters:
  AwsDefaultVpcId: vpc-9c70bbf9
  AwsSnsNotificationEndpoint: bridgeworker-prod@sagebase.org
  BackfillBucket: org-sagebridge-backfill-prod
  BridgeEnv: prod
  BridgeUser: heroku
  BridgeWorkerEmail: bridgeit+worker@sagebase.org
  BridgeWorkerStudy: api
  BridgeWorkerPassword: !ssm /bridgeworker-prod/BridgeWorkerPassword
  EC2InstanceType: t3a.2xlarge
  Env: production
  JavaHeapSize: 24g
  NewRelicAppName: bridgeworker-prod
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  RawHealthDataBucket: org-sagebridge-rawhealthdata-prod
  SynapseApiKey:  !ssm /bridgeworker-prod/SynapseApiKey
  SynapsePrincipalId: '3325672'
  SynapseUser: BridgeExporter
  UploadBucket: org-sagebridge-upload-prod
  UploadCertBucket: org-sagebridge-upload-cms-cert-prod
  UploadPrivateKeyBucket: org-sagebridge-upload-cms-priv-prod
  UserDataBucket: org-sagebridge-userdata-prod
  WorkerSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/649232250620/Bridge-WorkerPlatform-Request-prod
