template_path: templates/bridgeworker.yaml
stack_name: bridgeworker-prod
parameters:
  AwsDefaultVpcId: vpc-9c70bbf9
  AwsSnsNotificationEndpoint: bridgeworker-prod@sagebase.org
  BridgeEnv: prod
  BridgeUser: heroku
  BridgeWorkerEmail: bridgeit+worker@sagebase.org
  BridgeWorkerStudy: api
  BridgeWorkerPassword: !ssm /bridgeworker-prod/BridgeWorkerPassword
  EC2InstanceType: t2.micro
  Env: production
  AwsSolutionStackName: '64bit Amazon Linux 2017.09 v2.7.5 running Tomcat 8 Java 8'
  NewRelicAppName: bridgeworker-prod
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  SynapseApiKey:  !ssm /bridgeworker-prod/SynapseApiKey
  SynapsePrincipalId: '3325672'
  SynapseUser: BridgeExporter
  UserDataBucket: org-sagebridge-userdata-prod
