template_path: bridgeworker.yaml
stack_name: bridgeworker-prod
parameters:
  AwsDefaultVpcId: vpc-9c70bbf9
  AwsSnsNotificationEndpoint: bridgeworker-prod@sagebase.org
  BackfillBucket: org-sagebridge-backfill-prod
  BridgeEnv: prod
  BridgeUser: heroku
  BridgeWorkerEmail: bridgeit+worker@sagebase.org
  BridgeWorkerStudy: api
  BridgeWorkerPassword: !ssm /bridgeworker-prod/BridgeWorkerPassword
  EC2InstanceType: t2.micro
  Env: production
  NewRelicAppName: bridgeworker-prod
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  SynapseApiKey:  !ssm /bridgeworker-prod/SynapseApiKey
  SynapsePrincipalId: '3325672'
  SynapseUser: BridgeExporter
  UserDataBucket: org-sagebridge-userdata-prod
