template_path: templates/bridgeworker.yaml
stack_name: bridgeworker-{{ environment_variable.TRAVIS_BRANCH }}
parameters:
  AwsDefaultVpcId: {{ environment_variable.AwsDefaultVpcId_develop }}
  AwsSnsNotificationEndpoint: {{ environment_variable.AwsSnsNotificationEndpoint_develop }}
  BridgeEnv: {{ environment_variable.BridgeEnv_develop }}
  BridgeUser: {{ environment_variable.BridgeUser }}
  BridgeWorkerEmail: {{ environment_variable.BridgeWorkerEmail_develop }}
  BridgeWorkerStudy: {{ environment_variable.BridgeWorkerStudy_develop }}
  BridgeWorkerPassword: {{ environment_variable.BridgeWorkerPassword_develop }}
  EC2InstanceType: t2.micro
  Env: {{ environment_variable.Env_develop }}
  AwsSolutionStackName: {{ environment_variable.AwsSolutionStackName }}
  NewRelicAppName: bridgeworker-{{ environment_variable.TRAVIS_BRANCH }}
  NewRelicLicenseKey: {{ environment_variable.NewRelicLicenseKey }}
  SynapseApiKey: {{ environment_variable.SynapseApiKey_develop }}
  SynapsePrincipalId: "{{ environment_variable.SynapsePrincipalId_develop }}"
  SynapseUser: {{ environment_variable.SynapseUser_develop }}
  UserDataBucket: {{ environment_variable.UserDataBucket_develop }}
