template_path: bridgeworker.yaml
stack_name: bridgeworker-develop
parameters:
  AwsDefaultVpcId: vpc-f389e98a
  AwsSnsNotificationEndpoint: bridgeworker-develop@sagebase.org
  BackfillBucket: org-sagebridge-backfill-devdevelop
  BridgeEnv: dev
  BridgeUser: heroku
  BridgeWorkerEmail: bridgeit+worker@sagebase.org
  BridgeWorkerStudy: api
  BridgeWorkerPassword: !ssm /bridgeworker-develop/BridgeWorkerPassword
  EC2InstanceType: t2.micro
  Env: develop
  NewRelicAppName: bridgeworker-develop
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  RawHealthDataBucket: org-sagebridge-rawhealthdata-devdevelop
  SynapseApiKey:  !ssm /bridgeworker-develop/SynapseApiKey
  SynapsePrincipalId: '3330889'
  SynapseUser: BridgeExporterDev
  UploadBucket: org-sagebridge-upload-devdevelop
  UploadCertBucket: org-sagebridge-upload-cms-cert-devdevelop
  UploadPrivateKeyBucket: org-sagebridge-upload-cms-priv-devdevelop
  UserDataBucket: org-sagebridge-userdata-devdevelop
  WorkerSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/420786776710/Bridge-WorkerPlatform-Request-develop
