template_path: bridgeworker.yaml
stack_name: bridgeworker-develop
parameters:
  AwsDefaultVpcId: vpc-08383f78519fe72ef
  AwsSnsNotificationEndpoint: biaffect-bridge-ops-develop@googlegroups.com
  BackfillBucket: org-biaffectbridge-backfill-develop
  BridgeEnv: dev
  BridgeUser: biaffect
  BridgeWorkerEmail: biaffect-bridge-ops-develop+worker@googlegroups.com
  BridgeWorkerStudy: api
  BridgeWorkerPassword: !ssm /bridgeworker-develop/BridgeWorkerPassword
  EC2InstanceType: t3a.small
  Env: develop
  RawHealthDataBucket: org-biaffectbridge-rawhealthdata-develop
  SynapseAccessToken:  !ssm /bridgeworker-develop/SynapseAccessToken
  SynapsePrincipalId: '3509740'
  SynapseUser: BiaffectBridgeExporter
  UploadBucket: org-biaffectbridge-upload-develop
  UploadCertBucket: org-biaffectbridge-upload-cms-cert-develop
  UploadPrivateKeyBucket: org-biaffectbridge-upload-cms-priv-develop
  UserDataBucket: org-biaffectbridge-userdata-develop
  ParticipantRosterBucket: org-biaffectbridge-participantroster-develop
  WorkerSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/381492192635/Bridge-WorkerPlatform-Request-develop
