template_path: bridgeworker.yaml
stack_name: bridgeworker-develop
parameters:
  AwsDefaultVpcId: vpc-9c70bbf9
  AwsSnsNotificationEndpoint: bridgeworker-develop@sagebase.org
  BackfillBucket: org-sagebridge-backfill-develop
  BridgeEnv: dev
  BridgeUser: heroku
  BridgeWorkerEmail: bridgeit+worker@sagebase.org
  BridgeWorkerStudy: api
  BridgeWorkerPassword: !ssm /bridgeworker-develop/BridgeWorkerPassword
  EC2InstanceType: t2.micro
  Env: develop
  NewRelicAppName: bridgeworker-develop
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  SynapseApiKey:  !ssm /bridgeworker-develop/SynapseApiKey
  SynapsePrincipalId: '3330889'
  SynapseUser: BridgeExporterDev
  UserDataBucket: org-sagebridge-userdata-develop
