template_path: bridgeworker.yaml
stack_name: bridgeworker-uat
parameters:
  AwsDefaultVpcId: vpc-f389e98a
  AwsSnsNotificationEndpoint: bridgeworker-uat@sagebase.org
  BackfillBucket: org-sagebridge-backfill-devstaging
  BridgeEnv: uat
  BridgeUser: heroku
  BridgeWorkerEmail: bridgeit+worker@sagebase.org
  BridgeWorkerStudy: api
  BridgeWorkerPassword: !ssm /bridgeworker-uat/BridgeWorkerPassword
  EC2InstanceType: t3a.small
  Env: staging
  NewRelicAppName: bridgeworker-uat
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  RawHealthDataBucket: org-sagebridge-rawhealthdata-devstaging
  SynapseAccessToken:  !ssm /bridgeworker-uat/SynapseAccessToken
  SynapsePrincipalId: '3336429'
  SynapseUser: bridgetest
  UploadBucket: org-sagebridge-upload-devstaging
  UploadCertBucket: org-sagebridge-upload-cms-cert-devstaging
  UploadPrivateKeyBucket: org-sagebridge-upload-cms-priv-devstaging
  UserDataBucket: org-sagebridge-userdata-devstaging
  ParticipantRosterBucket: org-sagebridge-participantroster-devstaging
  WorkerSqsQueueUrl: https://sqs.us-east-1.amazonaws.com/420786776710/Bridge-WorkerPlatform-Request-staging
