template_path: bridgeworker.yaml
stack_name: bridgeworker-uat
parameters:
  AwsDefaultVpcId: vpc-9c70bbf9
  AwsSnsNotificationEndpoint: bridgeworker-uat@sagebase.org
  BackfillBucket: org-sagebridge-backfill-uat
  BridgeEnv: uat
  BridgeUser: heroku
  BridgeWorkerEmail: bridgeit+worker@sagebase.org
  BridgeWorkerStudy: api
  BridgeWorkerPassword: !ssm /bridgeworker-uat/BridgeWorkerPassword
  EC2InstanceType: t2.micro
  Env: staging
  NewRelicAppName: bridgeworker-uat
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  SynapseApiKey:  !ssm /bridgeworker-uat/SynapseApiKey
  SynapsePrincipalId: '3327942'
  SynapseUser: BridgeExporterStaging
  UserDataBucket: org-sagebridge-userdata-uat
